[package]
name = "sqlite-containers"
description = "SQLite-based containers for Rust"
version = "1.0.0"
edition = "2024"
rust-version = "1.88.0"
authors = ["Daniel Trick <daniel.trick@sit.fraunhofer.de>"]
license = "Unlicense"
repository = "https://github.com/danieltrick/sqlite-containers/"

[features]
default = ["bundled"]
bundled = ["rusqlite/bundled"]

[dependencies]
rand = "0.10.3"
rusqlite = "0.40.2"

[dev-dependencies]
criterion = { version = "0.8.2", default-features = false }
hex = "0.4.3"

[[bench]]
name = "sqlite_containers-bench"
harness = false
