name: Cargo Workflow

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Code checks
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  clippy:
    name: cargo clippy

    strategy:
      matrix:
        rust: ["1.88.0", "1.99.0"]
        platform:
          - host: ubuntu-26.04
            multilib: false
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-26.04
            multilib: true
            target: i686-unknown-linux-gnu
          - host: ubuntu-26.04-arm
            multilib: false
            target: aarch64-unknown-linux-gnu

    runs-on: ${{ matrix.platform.host }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.platform.target }}
          components: rustfmt clippy
          cache: false
      - if: ${{ matrix.platform.multilib }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib libc6-dev-i386
      - run: make clippy
        env:
          CARGO_BUILD_TARGET: ${{ matrix.platform.target }}

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Unit tests
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  tests:
    name: cargo test
    needs: clippy

    strategy:
      matrix:
        rust: ["1.88.0", "1.99.0"]
        platform:
          - host: ubuntu-26.04
            multilib: false
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-26.04
            multilib: true
            target: i686-unknown-linux-gnu
          - host: ubuntu-26.04-arm
            multilib: false
            target: aarch64-unknown-linux-gnu

    runs-on: ${{ matrix.platform.host }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.platform.target }}
          components: rustfmt clippy
          cache: false
      - if: ${{ matrix.platform.multilib }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib libc6-dev-i386
      - run: make test
        env:
          CARGO_BUILD_TARGET: ${{ matrix.platform.target }}
